name: Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "www/**"
      - ".github/workflows/deploy-www.yml"
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v4
      - uses: actions/setup-node@v4
      - run: npm ci -w www --ignore-scripts
      - run: npm run build -w www
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "www/dist/"
      - uses: actions/deploy-pages@v3
        id: deployment
